module.exports = {
  CANDLE_RESOLUTIONS: {
    1: "1m",
    3: "3m",
    5: "5m",
    15: "15m",
    30: "30m",
    60: "1h",
    120: "2h",
    240: "4h",
    360: "6h",
    480: "8h",
    720: "12h",
    D: "1d",
    "1D": "1d",
    "3D": "3d",
    W: "1w",
    "1W": "1w",
    M: "1M",
    "1M": "1M",
  },

  EXCHANGES: {
    BINANCE: "binance",
    BYBIT: "bybit",
    BLOFIN: "blofin",
    ALPACA: "alpaca",
    GECKO: "geckoterminal",
  },

  EVENT_TYPES: {
    KLINE: "kline",
    TRADE: "trade",
    TICKER: "ticker",
    ORDER_BOOK: "orderbook",
  },

  NORMALIZED_FIELDS: {
    TIMESTAMP: "timestamp",
    OPEN: "open",
    HIGH: "high",
    LOW: "low",
    CLOSE: "close",
    VOLUME: "volume",
    SYMBOL: "symbol",
    EXCHANGE: "exchange",
    RESOLUTION: "resolution",
  },

  INDICATORS: {
    SMA: "sma",
    EMA: "ema",
    RSI: "rsi",
    MACD: "macd",
    BB: "bollinger_bands",
    STOCH: "stochastic",
    ATR: "atr",
    OBV: "obv",
  },
};
